export const ONE_RM_PERCENTAGE = [
  100, 97, 94, 92, 89, 86, 83, 81, 78, 75, 73, 71,
];

export const ONE_RM_CALCULATION = [
  { repetitions: 1, percentage: 100, weight: 0, unit: "kg" },
  { repetitions: 2, percentage: 97, weight: 0, unit: "kg" },
  { repetitions: 3, percentage: 94, weight: 0, unit: "kg" },
  { repetitions: 4, percentage: 92, weight: 0, unit: "kg" },
  { repetitions: 5, percentage: 89, weight: 0, unit: "kg" },
  { repetitions: 6, percentage: 86, weight: 0, unit: "kg" },
  { repetitions: 7, percentage: 83, weight: 0, unit: "kg" },
  { repetitions: 8, percentage: 81, weight: 0, unit: "kg" },
  { repetitions: 9, percentage: 78, weight: 0, unit: "kg" },
  { repetitions: 10, percentage: 75, weight: 0, unit: "kg" },
  { repetitions: 11, percentage: 73, weight: 0, unit: "kg" },
  { repetitions: 12, percentage: 71, weight: 0, unit: "kg" },
  { repetitions: 13, percentage: 70, weight: 0, unit: "kg" },
  { repetitions: 14, percentage: 68, weight: 0, unit: "kg" },
  { repetitions: 15, percentage: 67, weight: 0, unit: "kg" },
  { repetitions: 16, percentage: 65, weight: 0, unit: "kg" },
  { repetitions: 17, percentage: 64, weight: 0, unit: "kg" },
  { repetitions: 18, percentage: 63, weight: 0, unit: "kg" },
  { repetitions: 19, percentage: 61, weight: 0, unit: "kg" },
  { repetitions: 20, percentage: 60, weight: 0, unit: "kg" },
  { repetitions: 21, percentage: 59, weight: 0, unit: "kg" },
  { repetitions: 22, percentage: 58, weight: 0, unit: "kg" },
  { repetitions: 23, percentage: 57, weight: 0, unit: "kg" },
  { repetitions: 24, percentage: 56, weight: 0, unit: "kg" },
  { repetitions: 25, percentage: 55, weight: 0, unit: "kg" },
  { repetitions: 26, percentage: 54, weight: 0, unit: "kg" },
  { repetitions: 27, percentage: 53, weight: 0, unit: "kg" },
  { repetitions: 28, percentage: 52, weight: 0, unit: "kg" },
  { repetitions: 29, percentage: 51, weight: 0, unit: "kg" },
  { repetitions: 30, percentage: 50, weight: 0, unit: "kg" },
];

export const BODY_FILTER = [
  { value: "biceps", label: "Biceps", type: "body" },
  { value: "triceps", label: "Triceps", type: "body" },
  { value: "back", label: "Back", type: "body" },
  { value: "chest", label: "Chest", type: "body" },
  { value: "legs", label: "Legs", type: "body" },
  { value: "shoulders", label: "Shoulders", type: "body" },
  { value: "abdominals", label: "Abdominals", type: "body" },
  { value: "forearms", label: "Forearms", type: "body" },
];

export const CATEGORY_FILTER = [
  { value: "barbell", label: "Barbell", type: "category" },
  { value: "dumbbell", label: "Dumbbell", type: "category" },
  { value: "machine", label: "Machine", type: "category" },
  {
    value: "body_only",
    label: "Bodyweight",
    type: "category",
  },
  { value: "bands", label: "Bands", type: "category" },
  { value: "e-z_curl_bar", label: "E-z curl bar", type: "category" },
  { value: "Cable", label: "cable", type: "category" },
  { value: "medicine_ball", label: "Medicine ball", type: "category" },
  { value: "foam_roll", label: "Foam roll", type: "category" },
  { value: "kettlebells", label: "Kettlebells", type: "category" },
  { value: "other", label: "Other", type: "category" },
];
